 steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t $$USERNAME/dbonk8s:latest .']
   secretEnv: ['USERNAME']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push $$USERNAME/dbonk8s:latest']
   secretEnv: ['USERNAME']
 availableSecrets:
   secretManager:
   - versionName: projects/linebot-371516/secrets/DOCKER_PASSWORD_SECRET/versions/1
     env: 'PASSWORD'
   - versionName: projects/linebot-371516/secrets/DOCKER_USERNAME_SECRET/versions/1
     env: 'USERNAME'
