apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
  - ./deployment-prod.yaml
configMapGenerator:
- name: env-vars
  behavior: merge
  envs:
  - ./base.env
secretGenerator:
  - name: env-secret
    behavior: replace
    envs:
      - ./secret.env
