apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: toc-linebot-crb
subjects:
- kind: ServiceAccount
  name: toc-linebot-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: toc-linebot-cr
  apiGroup: rbac.authorization.k8s.io

