apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: toc-linebot-cr
rules:
- apiGroups:
    - ""
  resources:
    - services
    - namespaces
    - pods
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - "apps"
  resources:
    - deployments
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
