apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./serviceaccount.yaml
  - ./clusterrole.yaml
  - ./clusterrolebinding.yaml
configMapGenerator:
  - name: env-vars
    envs:
      - ./base.env
secretGenerator:
  - name: env-secret
    envs:
      - ./secret.env
